include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables

